### ISSUE TITLE
Default size to prevent full screen svgs when using svg icons

### ISSUE THREAD

**Issue by Kturva** [driesvints/blade-icons#35]
Rendered svg icons might benefit from having a default fallback size to prevent them taking the entire screen if stylesheet with `.icon` definition is blocked or takes time to load.

Not sure how it would work though. Maybe a recommendation to add e.g. 
```
<style>
.icon { height: 1em; }
</style>
```
directly in html template? 🙂

**Comment by calebporzio** [comment]
I personally add something like this typically to `blade-svg`'s config file:

```php
'class' => 'svg',
```

`svg` is a custom CSS class I pass around that takes care of sizing:

```css
.svg {
    height: 1em;
    margin-top: -4px;
    pointer-events:none;
    vertical-align: middle;
    fill: currentColor;
    width: 1em;
}
```

Are you proposing adding a helpful note to the README or something else? I agree it's a common hiccup for people using this package. But I'm not sure it's the job of this package to remedy. Open though.
